######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 16 06:10:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Code Desktop
INCLUDEPATH += .

# Input
SOURCES += Code/run_while.c Desktop/cpu-temp.c Desktop/hello.c
